### ISSUE TITLE
Previous labels disappearing and color + height different

### ISSUE THREAD

**Issue by Benoit1980** [PH7-Jack/livewire-ui#558] opened 2022-12-02 14:35 UTC
Hello,

I just added your package to a current livewire project and all the labels are dissapearing.

Before(Labels + notice the fields height):
![1](https://user-images.githubusercontent.com/6231274/205316120-9f35770f-f3fa-4c37-b8b9-cbf06bebd8bf.jpg)

After installing your package(No more labels, borders have a different color and the height is different):
![2](https://user-images.githubusercontent.com/6231274/205316380-b305955b-b9d1-4d07-92e0-7e0fb971cf2e.jpg)

 ```
  "laravel/framework": "9.41.0",

"devDependencies": {
        "@tailwindcss/forms": "^0.4.0",
        "alpinejs": "^3.4.2",
        "autoprefixer": "^10.4.5",
        "axios": "^0.25",
        "flowbite": "^1.4.7",
        "laravel-mix": "^6.0.6",
        "lodash": "^4.17.19",
        "postcss": "^8.4.14",
        "postcss-import": "^12.0.1",
        "tailwindcss": "^3.0.0",
        "tailwindcss-animatecss": "^1.0.7",
        "vue-loader": "^16.8.3",
        "vue-template-compiler": "^2.7.7"
    },
    "dependencies": {
        "@tailwindcss/aspect-ratio": "^0.4.0",
        "daisyui": "2.19.0",
        "vue": "^3.2.36"
    }
```

Tailwind.config.js
```
const defaultTheme = require('tailwindcss/defaultTheme')
const colors = require("tailwindcss");
module.exports = {
    presets: [
        require('./vendor/wireui/wireui/tailwind.config.js')
    ],
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.vue',
        './node_modules/flowbite/**/*.js',
        './vendor/wireui/wireui/resources/**/*.blade.php',
        './vendor/wireui/wireui/ts/**/*.ts',
        './vendor/wireui/wireui/src/View/**/*.php'
    ],
    theme: {
        extend: {
            fontFamily: {
                montserrat: ['Montserrat'],
                sans: ['Inter var', ...defaultTheme.fontFamily.sans],
            },
            screens: {
                sm: '640px',
                md: '768px',
                lg: '1024px',
                xl: '1280px',
                '2xl': '1536px',
            },
            colors: {
                primary: colors.indigo,
                secondary: colors.gray,
                positive: colors.emerald,
                negative: colors.red,
                warning: colors.amber,
                info: colors.blue,
                transparent: 'transparent',
                current: 'currentColor',
                'facebook': '#3b5998',
                'twitter': '#00acee',
                'linkedin': '#0072b1',
                'whatsapp': '#25D366',
                'instagram': '#E4405F',
                'yellow': '#FFDD03',
                'yellow-form': '#FFDD0366',
                "red": {
                    "50": "#fe3232",
                    "100": "#f42828",
                    "200": "#ea1e1e",
                    "300": "#e01414",
                    "400": "#d60a0a",
                    "500": "#cc0000",
                    "600": "#c20000",
                    "700": "#b80000",
                    "800": "#ae0000",
                    "900": "#a40000"
                },
                "teal": {
                    "50": "#72e2f1",
                    "100": "#68d8e7",
                    "200": "#5ecedd",
                    "300": "#54c4d3",
                    "400": "#4abac9",
                    "500": "#40b0bf",
                    "600": "#36a6b5",
                    "700": "#2c9cab",
                    "800": "#2292a1",
                    "900": "#188897"
                },
                "green": {
                    "50": "#ffffbd",
                    "100": "#f5ffb3",
                    "200": "#ebffa9",
                    "300": "#e1ff9f",
                    "400": "#d7f595",
                    "500": "#cdeb8b",
                    "600": "#c3e181",
                    "700": "#b9d777",
                    "800": "#afcd6d",
                    "900": "#a5c363"
                },
                "blue": {
                    "50": "#72c8ff",
                    "100": "#68beff",
                    "200": "#5eb4ff",
                    "300": "#54aaff",
                    "400": "#4aa0f8",
                    "500": "#4096ee",
                    "600": "#368ce4",
                    "700": "#2c82da",
                    "800": "#2278d0",
                    "900": "#186ec6"
                },
                "orange": {
                    "50": "#ffa632",
                    "100": "#ff9c28",
                    "200": "#ff921e",
                    "300": "#ff8814",
                    "400": "#ff7e0a",
                    "500": "#ff7400",
                    "600": "#f56a00",
                    "700": "#eb6000",
                    "800": "#e15600",
                    "900": "#d74c00"
                },
                "black": {
                    "50": "#565555",
                    "100": "#4c4b4b",
                    "200": "#424141",
                    "300": "#383737",
                    "400": "#2e2d2d",
                    "500": "#242323",
                    "600": "#1a1919",
                    "700": "#100f0f",
                    "800": "#060505",
                    "900": "#000000"
                }
            },
        },
    },
    variants: {
        extend: {},
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/aspect-ratio'),
        require("daisyui"),
        require('flowbite/plugin')
    ],
}

```

Any idea why please?

Thank you.

**Comment by joaopalopes24** [comment] 2022-12-08 16:57
Try verifying the import on files in the layout file. But since this is not a bug, I will close this PR. Feel free to open a card in the Discussions tab. Thank you very much in advance.

[Documentation](https://livewire-wireui.com/docs/get-started)

**Closed as completed by joaopalopes24** 2022-12-08 16:57 UTC
