### ISSUE TITLE
Multi-selectable user selection in Select form

### ISSUE THREAD

**Issue by kai0310** [PH7-Jack/livewire-ui#669] opened 2023-05-29 20:21 UTC
As the title suggests, I am trying to perform multi-selectable user selection on a Select form.

I will work with a simple example from the official documentation.

The following code is passed as an argument to enable multiselect for the [Async Search example](https://livewire-wireui.com/docs/select#async-search).

However, this code fails to select multiple users. Is this not a bug, or does it mean that the argument is not valid and this feature is not yet implemented?

I would very much like to know the solution to fulfill this request.

## Code

```PHP
<x-select
    multiselect
    label="Search a User"
    wire:model.defer="model"
    placeholder="Select some user"
    :async-data="route('api.users.index')"
    option-label="name"
    option-value="id"
/>
```

## Result

https://github.com/wireui/wireui/assets/52205108/fd759ca4-fe5f-43e5-b9ce-36d33222f9e3

**Comment by joaopalopes24** [comment] 2023-05-29 21:42
@kai0310 I just tested it and it worked fine.

Is your `model` attribute an **array**?

**Comment by joaopalopes24** [comment] 2023-05-29 21:46
As this is not a bug, I will be closing your PR. Any questions just send them here.

**Closed as completed by joaopalopes24** 2023-05-29 21:46 UTC

**Comment by kai0310** [comment] 2023-05-30 01:47
@joaopalopes24 

Thank you for your prompt reply.

No, I have put null in the model as [per the demo in the official docs](https://github.com/wireui/docs/blob/main/app/Http/Livewire/Documentation/Select.php#LL175C1).
If possible, could you please let me know what properties you used for the validation?

**Comment by joaopalopes24** [comment] 2023-05-30 11:54
I don't understand your solicitation. You don't need to put null in the model.

Do you add the `wire:key` in your blade?

**Comment by kai0310** [comment] 2023-05-30 19:03
Oh I understand completely ....
It was a problem that depended on the array structure of the async data.
This was totally my problem.

At first glance it looks correct, but if there is a problem with the data structure, the selection may not be reflected correctly.


This is a slightly different story, but I thought it would be easier to understand if an example of the rendering code was also included in the documentation.
I hope this will be helpful.


Thank you.
