### ISSUE TITLE
x-on:selected not working when deselecting

### ISSUE THREAD

**Issue by pablomadariaga** [PH7-Jack/livewire-ui#546] opened 2022-11-23 04:34 UTC
In the select multiselect the `x-on:selected` event is not working when deselecting option.

This the Jam video.

https://jam.dev/c/9bc98585-76dc-4820-bdb3-128d2b200d67

This my code.

![image](https://user-images.githubusercontent.com/69119357/203469870-b7327d94-6fec-4ec4-80c4-a7d14444d090.png)

I think it would be better if 2 separate events were handled as they are 2 different actions

```
x-on:selected
x-on:deselected

```

**Comment by joaopalopes24** [comment] 2022-11-26 16:57
@pablomadariaga Check in documentation the `x-on:clear` event.

https://livewire-wireui.com/docs/select#select-events

**Comment by pablomadariaga** [comment] 2022-11-26 17:07
> @pablomadariaga Check in documentation the `x-on:clear` event.
> 
> https://livewire-wireui.com/docs/select#select-events

The `x-on:clear` event works, but when doing a general clear, not when clearing a single selection from a `select multiple`

**Comment by pablomadariaga** [comment] 2022-12-06 15:44
Is there any solution?

**Comment by joaopalopes24** [comment] 2022-12-06 16:04
@pablomadariaga We will think about this implementation only for v2. In addition, we will not make any feature at the moment for this type of functionality.

**Comment by joaopalopes24** [comment] 2022-12-08 16:52
This issue will be closed as it is not a bug. We will implement it in version 2, but at the moment we will not put this feature.

**Closed as completed by joaopalopes24** 2022-12-08 16:52 UTC

**Comment by pablomadariaga** [comment] 2022-12-08 21:22
ok
