### ISSUE TITLE
Unable to locate a class or view for component [inputs.password]

### ISSUE THREAD

**Issue by agharium** [PH7-Jack/livewire-ui#529] opened 2022-11-12 21:16 UTC
**Describe the bug**
Trying to use the password input, getting "Unable to locate a class or view for component [inputs.password]".

**To Reproduce**
1. Just code a "<x-inputs.password />"
2. See error

```
<x-input label="Nome" /> // works
<x-input label="Usuário" /> // works
<x-inputs.password label="Nova senha" /> // doesn't work at all
````

**Expected behavior**
It should work as in documentation.

**Additional context**
Looking into the vendor folder, the actual file isn't there:

![image](https://user-images.githubusercontent.com/28984633/201494798-b23724eb-e359-4245-8fed-51695b60fb03.png)

What's going on..?

Thanks for your attention, loving the package so far, so so useful!

**Comment by joaopalopes24** [comment] 2022-11-12 22:53
@agharium Password input was inserted into the package in version 1.15. Check if the package is up to date in your project, and if I have published the config, check if it is in the component array.

Release: https://github.com/wireui/wireui/releases/tag/v1.15.0

**Comment by joaopalopes24** [comment] 2022-11-12 22:54
I thank the attention. I will close this issue as it is not a bug.

**Closed as completed by joaopalopes24** 2022-11-12 22:54 UTC
Labels: Resolved
