### ISSUE TITLE
jetstream components collides with wire ui

### ISSUE THREAD

**Issue by Mohsin1931** [PH7-Jack/livewire-ui#667] opened 2023-05-25 16:33 UTC
After installing wire ui along with jetstream. jetstream components are colliding with wire ui components and x-label and all the others are not working for jetstream because the syntax for using both is same!!!!

**Comment by madushancs** [comment] 2023-05-26 03:50
> After installing wire ui along with jetstream. jetstream components are colliding with wire ui components and x-label and all the others are not working for jetstream because the syntax for using both is same!!!!

Hi Mohsin, I also have the same issue but one member of wireUI recommended, pass the all JetStream components to use the WireUI one. (https://github.com/wireui/wireui/issues/663).

**Comment by AnassGBNL** [comment] 2023-05-28 15:25
Does anyone already have fix for this issue?

**Comment by madushancs** [comment] 2023-05-28 15:32
> Does anyone already have fix for this issue?

no, I removed the wireUI temporarily until fixing this issue. I suppose this will fix soon.

**Comment by AnassGBNL** [comment] 2023-05-28 15:35
I came across an issue discussing Livewire Breeze, which seems to have the same issue. Additionally, @Mohsin1931  mentioned something about modifying the wireui config file. I am currently investigating this solution and will inform you whether it proves successful.

**Comment by AnassGBNL** [comment] 2023-05-28 15:44
> > Does anyone already have fix for this issue?
> 
> no, I removed the wireUI temporarily until fixing this issue. I suppose this will fix soon.

@madushancs  I found a solution look at the other open issue (https://github.com/wireui/wireui/issues/663). It worked for me. If you need any help you can @ me.

**Comment by madushancs** [comment] 2023-05-29 00:35
> > > Does anyone already have fix for this issue?
> > 
> > 
> > no, I removed the wireUI temporarily until fixing this issue. I suppose this will fix soon.
> 
> @madushancs I found a solution look at the other open issue (#663). It worked for me. If you need any help you can @ me.

Thanks

**Comment by joaopalopes24** [comment] 2023-05-29 10:57
Hello guys, this is not a bug, just a component conflict. You can rename the WireUI components in your config, or start using the WireUI components within Laravel Breeze and Jetstream (which is usually what I do). Therefore, I will be closing this Issue, thank you.

**Closed as completed by joaopalopes24** 2023-05-29 10:57 UTC
Labels: Bug
